### PR TITLE
Generation of DjVu from JP2 files

### PR DESCRIPTION
**Pull request by samwilson**
This adds a new system for producing DjVu files for IA items.

The biggest two parts of this are
* a way to choose what the DjVu is created from (DjVu, JP2, or PDF);
* and shifting the actually processing and uploading to a CLI.

### CODE REVIEW

**Comment by Tpt** [comment]
Thank you so much for working on it.

A deployment thing we should care about: the DjVu generation should probably be done on Tools Labs grid as it's probably a power intensive process. Doc: https://wikitech.wikimedia.org/wiki/Help:Tool_Labs/Grid

**Comment by samwilson** [comment]
Yes, good point about using the Grid. My plan is to have DjVu-conversion jobs processed on the grid, launched  every 1 minute or so. And to have a status list of current jobs on the homepage of the tool.

It'll have to save people's oauth tokens for the duration of the processing. I'll make sure this is very clear in the UI, and that the `job.json` files that store this info are only readable by the ia-upload user.

**Comment by samwilson** [comment]
This is also being tracked at https://phabricator.wikimedia.org/T154538

**Comment by kaldari** [comment]
According to the Phab ticket, this should be ready to merge. Please test and see if there are any last-minute kinks to work out.

**Comment by samwilson** [comment]
This is also being tracked at https://phabricator.wikimedia.org/T157410

**Comment by samwilson** [comment]
Deployed to production.

**Pull request merged**
