### PR TITLE
Normalize language code eng to en

### PR DESCRIPTION
**Pull request by samwilson**
Bug: T261111

### CODE REVIEW

**Comment by samwilson** [comment]
This is a hack, but works :shrug:

**Comment by Tpt** [comment]
We should probably make this for all languages have both a 3 characters and a 2 characters version. [Locale::canonicalize](https://www.php.net/manual/locale.canonicalize.php) seems to do it properly.

**Comment by samwilson** [comment]
Oh good point, thanks. Done.

**Comment by samwilson** [comment]
Thanks!

I've updated toolforge.

**Pull request merged**
