### PR TITLE
Finish switching to Intuition from SimpleI18N

### PR DESCRIPTION
**Pull request by samwilson**
A follow up from #62.

Bug: T370133

### CODE REVIEW

**Comment by Uzume** [comment]
I am wondering why this was in parts months apart.

**Comment by samwilson** [comment]
I guess because I'm busy and this wasn't a high priority, and no one else did it in the meantime.

The production instance hasn't been updated with any of this work yet, if you're asking why no one noticed this bug.

**Comment by Uzume** [comment]
So it was only deployed on [ia-upload-test](https://ia-upload-test.wmcloud.org/)?

Well it would be hard to notice many bugs right now in lieu of [T379402](https://phabricator.wikimedia.org/T379402).

Anyway, thank you for the update.

**Comment by samwilson** [comment]
No, it wasn't deployed to the test site either.

I'll get the test site working again. I didn't think anyone was using it.

**Pull request merged**
